name: Bump package version
on:
  workflow_dispatch:
    inputs:
      rule:
        type: choice
        description: Version bump level
        options:
        - major
        - minor
        - patch
        - premajor
        - preminor
        - prepatch
        - prerelease
        - "prerelease --next-phase"

jobs:
  bump:
    name: Bump version number
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.7.0"

      - name: Bump package Version using Poetry
        id: bumping
        env:
          RULE: ${{ github.event.inputs.rule }}
        run: echo "BUMP_MSG=$(poetry version $RULE)" >> $GITHUB_OUTPUT

      - name: Output debug msg
        env:
          BUMP_MSG: ${{ steps.bumping.outputs.BUMP_MSG }}
        run: echo "$BUMP_MSG"

      - name: Commit changes
        # could also use https://github.com/stefanzweifel/git-auto-commit-action instead
        env:
          BUMP_MSG: ${{ steps.bumping.outputs.BUMP_MSG }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "$BUMP_MSG"
          git push
