name: debug
on:
  release:
    types:
      - created
      - edited

jobs:
  edited:
    name: Draft edited
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: debug
        env:
          XY: ${{ github.event.action }}
        run: echo "## $XY" >> $GITHUB_STEP_SUMMARY

      - name: debug
        env:
          XY: ${{ github.event.release.body }}
        run: echo "$XY" >> $GITHUB_STEP_SUMMARY

      - name: debug
        env:
          XY: ${{ github.event.release.draft }}
        run: echo "**$XY**" >> $GITHUB_STEP_SUMMARY
