name: Replace version placeholders
on:
  workflow_dispatch:
    inputs:
      pkg-path:
        type: string
        description: Package path where to look for placeholders
        required: true
      file-pattern:
        type: string
        description: Glob pattern for files to find
        required: false
        default: "*.py"

jobs:
  replace:
    uses: AstarVienna/DevOps/.github/workflows/replaceholder.yml@main
    secrets: inherit
    with:
      pkg-path: ./astar_utils
